import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="">
        <div id="top-header" className=""></div>
        <nav className="">
          <img className=""></img>
        </nav>
      </header>
      <div id="hero" className="mt-5 h-75">
        <div className="d-grid gap-3 mx-auto text-center container">
          <h1>Welcome to Survey Manager</h1>
          <h4 className="">Manage your forms in a simple way, we recommend to read first <a href="#learn">this</a> section</h4>
          <button>
            <a href="/mysurveys">Let's start</a>
          </button>
        </div>
      </div>
      <section id="learn" className="my-5">
          <div className="container">
          <h3>How it works?</h3>
          <p>Keep track of forms and related data.<br/> Our application solves that problem by allowing you to create forms with unlimited values and link them to sub-level forms. This makes it easier for you to manage complex data structures and generate reports that provide a comprehensive view of all related data.</p>
          <p>Our platform offers a simple and intuitive interface, allowing you to quickly create and customize your forms. With our drag-and-drop builder, you can easily add fields, labels, and other elements to your forms, making it easy for you to capture the data you need.</p>
         <p>But that's not all! Our advanced linking feature allows you to connect your forms with sub-forms, creating a hierarchy of data that makes it easier for you to analyze and generate detailed reports. You can easily generate simple reports for your individual forms or dive into the more complex data relationships with our multi-level report feature.</p>
         <p>With our application, you can now take control of your data, and make informed business decisions that lead to success. Try it out now and see the difference it can make for your organization!</p>
          </div>
      </section>
    </>
  );
}
