import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="">
        <div id="top-header" className=""></div>
        <nav className="">
          <img className=""></img>
        </nav>
      </header>
      <div className="mt-5 h-75">
        <div className="d-grid gap-3 mx-auto text-center">
          <h1>Welcome to Survey builder</h1>
          <h2>Manage your forms</h2>
          <button>
            <a href="/mysurveys">Let's start</a>
          </button>
        </div>
      </div>
    </>
  );
}
