import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { Layout } from './[id]/Layout'
import 'bootstrap/dist/css/bootstrap.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className='page-header'>
        <div id="top-header" className="" ></div>
      <nav className=''>
        <img className=''></img>

        </nav>
      </header>
      <main>
        
        <div className='d-flex flex-row justify-content-center align-items-center'>
        <h1>Welcome to Survey builder</h1>
        <h2>Manage your forms</h2>
        <button><a href='/mysurveys'>Let's start</a></button>
      </div>

      </main>
      
    </>
  )
}
